### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by sukazavr** [watermarkchurch/ts-generators#1]
```bash
An unexpected error occurred! TypeError: Cannot read property 'map' of undefined
    at ContentfulTSGenerator.<anonymous> (C:\Users\sukaz\Downloads\gg content types\node_modules\contentful-ts-generator\dist\generator.js:78:78)
    at step (C:\Users\sukaz\Downloads\gg content types\node_modules\contentful-ts-generator\dist\generator.js:32:23)
    at Object.next (C:\Users\sukaz\Downloads\gg content types\node_modules\contentful-ts-generator\dist\generator.js:13:53)
    at fulfilled (C:\Users\sukaz\Downloads\gg content types\node_modules\contentful-ts-generator\dist\generator.js:4:58)
```

It looks like ContentfulTSGenerator is incompatible with modern ContentType, coz there is no `schema.contentTypes` property.

## Steps to reproduce:

1. Get the schema file:
```JavaScript
const contentful = require("contentful-management");
const fs = require("fs");

const client = contentful.createClient({
  accessToken: "---"
});

client
  .getSpace("---")
  .then(space => space.getContentTypes())
  .then(
    response =>
      new Promise(res =>
        fs.writeFile("myjsonfile.json", JSON.stringify(response), "utf8", res)
      )
  )
  .catch(console.error);
```

2. Run CLI command
```bash
contentful-ts-generator -f myjsonfile.json -o t
```

### Why didn't use CLI download schema command?
```bash
contentful-ts-generator -d -m MY_KEY -s MY_SPACE_ID
```
Unfortunately, there is a couple issues:
1. Error: Cannot find module 'yargs'
2. After manual installation of `yargs` module, you will get:
```bash
An unexpected error occurred! Error: No managementToken given!
    at new SchemaDownloader (C:\Users\sukaz\Downloads\gg content types\node_modules\contentful-ts-generator\dist\schema-downloader\index.js:71:19)
    at C:\Users\sukaz\Downloads\gg content types\node_modules\contentful-ts-generator\dist\main.js:96:34
    at step (C:\Users\sukaz\Downloads\gg content types\node_modules\contentful-ts-generator\dist\main.js:43:23)
    at Object.next (C:\Users\sukaz\Downloads\gg content types\node_modules\contentful-ts-generator\dist\main.js:24:53)
    at C:\Users\sukaz\Downloads\gg content types\node_modules\contentful-ts-generator\dist\main.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\sukaz\Downloads\gg content types\node_modules\contentful-ts-generator\dist\main.js:14:12)
    at Run (C:\Users\sukaz\Downloads\gg content types\node_modules\contentful-ts-generator\dist\main.js:90:12)
    at Object.<anonymous> (C:\Users\sukaz\Downloads\gg content types\node_modules\contentful-ts-generator\dist\main.js:149:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
```

**Comment by wawoon** [comment]
>It looks like ContentfulTSGenerator is incompatible with modern ContentType, coz there is no schema.contentTypes property.

I faced this problem when the nested content type has image assets.

for example

Shop has_many Product
Product has_many ProductFeature
ProductFeature has images

When we query a product, the ProductFeature's image url should be accessed by

```
shop.fields.products[0].fields.productFeatures[0].images[0].fields.file.url
```

but the Image's type doesn't have `fields` property.

**Comment by gburgett** [comment]
Hi @wawoon ! The `shop.fields.products[0]` is most likely an unresolved link.  If you hover over the `products` name inside of your IDE, it will likely tell you it is an `Array<ILink<'Entry'> | Product>`.  

One way to work with it is to use the wrapper classes.  Do it like this:
```ts
import {
  Shop
} from './lib/contentful/generated'

// Make sure you set the "resolve" parameter to actually get all the linked entries!!!
const shop = new Shop(client.getEntry(...), { resolve: 3 })
shop.fields.products[0].fields.productFeatures[0].images[0].fields.file.url
```

**Comment by gburgett** [comment]
@sukazavr I'm sorry I forgot to add `yargs` to the package.json!  I'll do that shortly.  I primarily use it via the webpack plugin method so I haven't used it with the CLI.

Also, it looks like I forgot to pass in the management token to the downloader!
```ts
const downloader = new SchemaDownloader({
      directory: path.dirname(args.file),
      filename: path.basename(args.file),
      logger,
    })
```
https://github.com/watermarkchurch/ts-generators/blob/master/packages/contentful-ts-generator/src/main.ts#L65

Again, my bad.  I'll fix those sometime today.

**Comment by gburgett** [comment]
Try installing 0.2.3
