### ISSUE TITLE
TypeError: ContentfulTsGeneratorPlugin is not a constructor

### ISSUE THREAD

**Issue by exdeniz** [watermarkchurch/ts-generators#2]
I try add generator to next.config.js and simple webpack config.  I have this error for next:
```
TypeError: ContentfulTsGeneratorPlugin is not a constructor
    at Object.webpack (/Volumes/New/Project/ecuresearch/new/next.config.js:23:7)
    at Object.webpack (/Volumes/New/Project/ecuresearch/new/node_modules/@zeit/next-css/index.js:30:27)
    at getBaseWebpackConfig (/Volumes/New/Project/ecuresearch/new/node_modules/next/dist/build/webpack-config.js:39:1600)
error Command failed with exit code 1.
```

and this for simple webpack:
```
/Volumes/New/Project/experement/webpack template/node_modules/webpack-cli/bin/cli.js:244
                                throw err;
                                ^

TypeError: ContentfulTsGeneratorPlugin is not a constructor
    at Object.<anonymous> (/Volumes/New/Project/experement/webpack template/webpack.config.js:57:5)
    at Module._compile (/Volumes/New/Project/experement/webpack template/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (/Volumes/New/Project/experement/webpack template/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/Volumes/New/Project/experement/webpack template/node_modules/webpack-cli/bin/convert-argv.js:133:13)
    at requireConfig (/Volumes/New/Project/experement/webpack template/node_modules/webpack-cli/bin/convert-argv.js:135:6)
    at /Volumes/New/Project/experement/webpack template/node_modules/webpack-cli/bin/convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (/Volumes/New/Project/experement/webpack template/node_modules/webpack-cli/bin/convert-argv.js:140:15)
    at yargs.parse (/Volumes/New/Project/experement/webpack template/node_modules/webpack-cli/bin/cli.js:241:39)
    at Object.parse (/Volumes/New/Project/experement/webpack template/node_modules/yargs/yargs.js:563:18)
    at /Volumes/New/Project/experement/webpack template/node_modules/webpack-cli/bin/cli.js:219:8
    at Object.<anonymous> (/Volumes/New/Project/experement/webpack template/node_modules/webpack-cli/bin/cli.js:538:3)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Volumes/New/Project/experement/webpack template/node_modules/webpack/bin/webpack.js:155:2)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
error Command failed with exit code 1.
```

webpack config:
```
const ContentfulTsGeneratorPlugin = require('contentful-ts-generator')
 new ContentfulTsGeneratorPlugin({
      outputDir: '/contentful',
      downloadSchema: true,
      space: 'xxx',
      environment: 'master',
      managementToken: 'xxx'
    })
```

**Comment by gburgett** [comment]
Ah, you are importing it the wrong way.  It is exposed as a property on the module.  Try this:

```js
const ContentfulTsGenerator = require('contentful-ts-generator')
 new ContentfulTsGenerator.ContentfulTsGeneratorPlugin({
      outputDir: '/contentful',
      downloadSchema: true,
      space: 'xxx',
      environment: 'master',
      managementToken: 'xxx'
    })
```

Usually if possible you should use the import syntax to get the plugin:
```ts
import { ContentfulTsGeneratorPlugin } from 'contentful-ts-generator'
```
